---
- name: Validate PostgreSQL credentials
  ansible.builtin.assert:
    that:
      - postgresql_password | length >= 16
    fail_msg: PostgreSQL password must contain at least 16 characters.
  no_log: true
