---
galaxy_info:
  role_name: application_service
  author: neutron-1985
  description: Validates, deploys, and manages the application container
  license: UNLICENSED
  min_ansible_version: "2.18"
  galaxy_tags:
    - application
    - docker

dependencies: []
