---
- name: Validate firewall policy inputs
  ansible.builtin.import_tasks: validate.yml

- name: Install firewall
  ansible.builtin.import_tasks: install.yml

- name: Configure firewall policy
  ansible.builtin.import_tasks: configure.yml
