---
- name: Check whether the Certbot timer unit is installed
  ansible.builtin.stat:
    path: "{{ tls_certificate_timer_unit_path }}"
  register: tls_certificate_timer

- name: Enable automatic certificate renewal
  ansible.builtin.systemd:
    name: "{{ tls_certificate_timer_unit }}"
    state: started
    enabled: true
    daemon_reload: true
  when:
    - >-
      not ansible_check_mode
      or tls_certificate_timer.stat.exists | default(false)
