---
- import_playbook: playbooks/infrastructure.yml
- import_playbook: playbooks/provision.yml
- import_playbook: playbooks/runtime.yml
- import_playbook: playbooks/gateway.yml
- import_playbook: playbooks/verify.yml
