---
- name: Create application persistent directories
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ vault_inventory.deploy_user }}"
    group: docker
    mode: "{{ item.mode }}"
  loop:
    - path: "{{ app_data_dir }}"
      mode: "0755"
    - path: "{{ app_uploads_dir }}"
      mode: "0777"
