---
- name: Remove application container
  community.docker.docker_container:
    name: "{{ app_container_name }}"
    state: absent
    force_kill: true
  when: infrastructure_reset_docker_info.rc == 0

- name: Remove application data and logs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ app_data_dir }}"
    - "{{ infrastructure_reset_app_log_dir }}"
