---
- name: Validate PostgreSQL service configuration
  ansible.builtin.import_tasks: validate.yml

- name: Deploy PostgreSQL service
  ansible.builtin.import_tasks: deploy_container.yml

- name: Reconcile PostgreSQL credentials
  ansible.builtin.import_tasks: reconcile_credentials.yml
