---
- name: Add deployment users
  ansible.builtin.user:
    name: "{{ item.name }}"
    groups: "{{ item.groups }}"
    append: true
    state: present
    shell: /bin/bash
  loop: "{{ deployment_access_users }}"

- name: Add deployment public key to authorized_keys
  ansible.posix.authorized_key:
    user: "{{ ssh_inventory.deploy_user }}"
    key: "{{ ssh_inventory.deploy_authorized_key }}"
    path: "{{ deployment_access_authorized_keys_path }}"
    state: present
