---
object_storage_host_previous_allowed_cidrs: >-
  {{ ansible_local.object_storage_firewall | default([]) }}
object_storage_host_fact_file: >-
  {{ ansible_local_facts_dir }}/object_storage_firewall.fact
object_storage_host_firewall_comment: project-devops-object-storage

