---
- name: Copy changes made during initial object storage synchronization
  ansible.builtin.include_tasks: synchronize.yml

- name: Stop source object storage provider
  ansible.builtin.include_role:
    name: object_storage_deploy
    tasks_from: stop_inactive

- name: Switch target provider to primary S3 port
  ansible.builtin.include_role:
    name: object_storage_deploy
    tasks_from: deploy
  vars:
    object_storage_deploy_api_port: "{{ object_storage_api_port }}"
    object_storage_deploy_console_enabled: true

