---
nginx_server_name: _
nginx_listen_port: "80"
nginx_app_upstream: http://127.0.0.1:8080
nginx_uploads_enabled: false
nginx_uploads_upstream: ""
nginx_uploads_bucket: ""
nginx_client_max_body_size: 20m

nginx_static_cache_path: /var/cache/nginx/project-static
nginx_static_cache_max_size: 256m
nginx_uploads_cache_path: /var/cache/nginx/project-uploads
nginx_uploads_cache_max_size: 1g
