---
database_host: "{{ hostvars[groups['database'] | first].ansible_host }}"
database_port: "5432"
database_name: bulletins
database_username: bulletins_app
database_password: "{{ database_vault.postgresql_password }}"
database_url: >-
  jdbc:postgresql://{{ database_host }}:{{ database_port }}/{{ database_name }}
