---
object_storage_bucket: bulletin-images
object_storage_region: us-east-1
object_storage_object_prefix: bulletins
object_storage_policy_name: bulletins-app-read-write
object_storage_access_key: bulletins-app
object_storage_secret_key: "{{ vault_s3_app_secret_key }}"

minio_root_user: bulletins-storage-admin
minio_root_password: "{{ vault_minio_root_password }}"
