---
- name: Create PostgreSQL data directory
  ansible.builtin.file:
    path: "{{ postgresql_data_dir }}"
    state: directory
    owner: "{{ postgresql_container_uid }}"
    group: "{{ postgresql_container_gid }}"
    mode: "0700"
