---
postgresql_data_dir: /var/lib/project-devops-postgresql/data
postgresql_container_uid: "70"

postgresql_fact_dir: /etc/ansible/facts.d
postgresql_fact_file: "{{ postgresql_fact_dir }}/postgresql_firewall.fact"
postgresql_firewall_comment: project-devops-postgresql
postgresql_previous_allowed_cidrs: "{{ ansible_local.postgresql_firewall | default([]) }}"
