---
postgresql_data_dir: "{{ postgresql_root_dir }}/data"
postgresql_container_uid: "70"
postgresql_container_gid: "70"

postgresql_fact_dir: /etc/ansible/facts.d
postgresql_firewall_comment: project-devops-postgresql
postgresql_previous_allowed_cidrs: "{{ ansible_local.postgresql_firewall | default([]) }}"
