---
- name: Wait until application is ready
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ app_management_port }}/actuator/health/readiness"
    status_code: 200
  register: app_verified_readiness
  retries: "{{ app_healthcheck_retries }}"
  delay: "{{ app_healthcheck_delay }}"
  until: app_verified_readiness.status == 200
  when: not ansible_check_mode

- name: Check application public endpoint
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ app_public_port }}{{ app_healthcheck_path }}"
    status_code: "{{ app_healthcheck_status_codes }}"
  register: app_verified_public_endpoint
  retries: "{{ app_healthcheck_retries }}"
  delay: "{{ app_healthcheck_delay }}"
  until: app_verified_public_endpoint.status in app_healthcheck_status_codes
  when: not ansible_check_mode
