---
- name: Allow application TCP ports
  community.general.ufw:
    rule: allow
    direction: in
    port: "{{ item }}"
    proto: tcp
    comment: "{{ server_provision_application_firewall_comment }}"
  loop: "{{ server_provision_application_ports }}"
