---
- name: "Step 2 | Provision database hosts"
  hosts: database
  remote_user: "{{ ssh_inventory.provision_user }}"
  become: true
  tags:
    - step_02
    - database

  roles:
    - role: common/host_prerequisites
    - role: geerlingguy.docker
    - role: common/deployment_access
    - role: common/firewall_policy
    - role: database/host
    - role: database/firewall

- name: "Step 2 | Run PostgreSQL container"
  hosts: database
  remote_user: "{{ ssh_inventory.deploy_user }}"
  become: false
  gather_facts: false
  tags:
    - step_02
    - database

  roles:
    - role: database/service
    - role: database/service_smoke_test
