---
- name: "Step 1 | Provision application hosts"
  hosts: application
  remote_user: "{{ vault_inventory.provision_user }}"
  become: true
  tags:
    - step_01
    - provision

  roles:
    - role: geerlingguy.docker
    - role: deployment_access
    - role: firewall_policy
      firewall_policy_allowed_tcp_ports:
        - "{{ app_public_port }}"
      firewall_policy_revoked_tcp_ports:
        - "{{ nginx_http_port }}"
        - "{{ nginx_https_port }}"
        - "{{ app_container_management_port }}"
