---
- name: "Step 1 | Prepare application server infrastructure"
  hosts: application
  remote_user: "{{ ssh_inventory.provision_user }}"
  become: true
  tags:
    - step_01
    - application

  roles:
    - role: common/host_prerequisites
    - role: geerlingguy.docker
    - role: common/deployment_access
    - role: common/firewall_policy
    - role: application/host
