---
- name: Render deployment configuration
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"

  vars_files:
    - ../group_vars/all/vault.yml
    - ../group_vars/all/vars.yml

  tasks:
    - name: Render production inventory
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/inventory.ini.j2"
        dest: "{{ playbook_dir }}/../generated.inventory.ini"
        mode: "0600"

    - name: Render SSH known hosts
      ansible.builtin.template:
        src: "{{ playbook_dir }}/../templates/known_hosts.j2"
        dest: "{{ playbook_dir }}/../generated.known_hosts"
        mode: "0600"
