---
- name: Reset project resources
  hosts: infrastructure
  remote_user: "{{ ssh_inventory.provision_user }}"
  become: true
  tags: reset

  vars:
    reset_scope: all

  roles:
    - role: environment_reset
      when: reset_scope == 'environment'
    - role: infrastructure_reset
      when: reset_scope == 'all'
