---
- name: Remove PostgreSQL container
  community.docker.docker_container:
    name: "{{ postgresql_container_name }}"
    state: absent
    force_kill: true
  when: infrastructure_reset_docker_info.rc == 0

- name: Remove PostgreSQL data
  ansible.builtin.file:
    path: "{{ postgresql_root_dir }}"
    state: absent

- name: Remove PostgreSQL firewall local fact
  ansible.builtin.file:
    path: "{{ postgresql_fact_file }}"
    state: absent
